### ISSUE TITLE
tensor dimension mismatch

### ISSUE THREAD

**Issue by vincent507cpu** [DRSY/KV_Compression#4]
```
Traceback (most recent call last):
  File "/home/zwj/GitHub/KV_Compression-main/run_clm_kv_compression.py", line 923, in <module>
    main()
  File "/home/zwj/GitHub/KV_Compression-main/run_clm_kv_compression.py", line 812, in main
    outputs = model(**batch)
              ^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/peft/peft_model.py", line 1083, in forward
    return self.base_model(
           ^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 161, in forward
    return self.model.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 1034, in forward
    outputs = self.gpt_neox(
              ^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 925, in forward
    outputs = layer(
              ^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 690, in forward
    attention_layer_outputs = self.attention(
                              ^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 213, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/llm/lib/python3.11/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 287, in _attn
    attn_scores = attn_scores + attention_mask
                  ~~~~~~~~~~~~^~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (256) must match the size of tensor b (65536) at non-singleton dimension 3
```

**Comment by vincent507cpu** [comment]
我的分析是：`attention_mask` 是三维的（batch, seq_len, seq_len），与 `attn_score` 维度不符（batch, seq_len）
